[package]
name = "phase1-probe"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
custom-heap = []
custom-panic = []
no-entrypoint = []
phase2-instrumentation = []

[dependencies]
borsh.workspace = true
solana-program.workspace = true
winter-math.workspace = true
winterfell.workspace = true
